FROM golang:1.23-alpine

WORKDIR /app

# Install air for hot reload
RUN go install github.com/air-verse/air@v1.52.3

# Install dependencies
RUN apk add --no-cache git ca-certificates tzdata

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Run with air for hot reload
CMD ["air", "-c", ".air.toml"]
