-- Seed websites data
-- Generated from user input

INSERT INTO websites (url, name, description, is_active, check_interval, timeout, status) VALUES
('https://aduancsirt.baliprov.go.id', 'AduanCSIRT', 'Sistem tiket aduan kerentanan Insiden Siber', 1, 5, 30, 'unknown'),
('https://antrean.baliprov.go.id', 'Antrean Backend', 'Sistem antrean untuk membantu masyarakat dalam mengakses antrean layanan kesehatan di Provinsi Bali (admin dan backend)', 1, 5, 30, 'unknown'),
('https://app-antrean.baliprov.go.id', 'Antrean Frontend', 'Sistem antrean untuk membantu masyarakat dalam mengakses antrean layanan kesehatan di Provinsi Bali (frontend)', 1, 5, 30, 'unknown'),
('https://hadir-app.baliprov.go.id', 'Aplikasi Absensi', 'Absensi seluruh pegawai di Provinsi Bali', 1, 5, 30, 'unknown'),
('https://aset.baliprov.go.id', 'Aset', 'Sistem sewa aset daerah provinsi bali', 1, 5, 30, 'unknown'),
('https://assessmentcenter.baliprov.go.id', 'Assessment Center', 'Website resmi UPTD. Penilaian Kompetensi Pegawai BKPSDM Provinsi bali', 1, 5, 30, 'unknown'),
('https://assets-spbe.baliprov.go.id', 'Assets SPBE', 'Assets SPBE', 1, 5, 30, 'unknown'),
('https://balailabkes.baliprov.go.id', 'Balai Labkes', 'Website resmi UPTD Balai Labkes Kerthi Bali Sadhajiwa Provinsi Bali', 1, 5, 30, 'unknown'),
('https://balicorpu.baliprov.go.id', 'Bali Corpu', 'Media peningkatan mutu sumber daya manusia oleh BKPSDM Provinsi Bali', 1, 5, 30, 'unknown'),
('https://digifest.baliprov.go.id', 'Bali Digifest', 'Website terkait informasi kegiatan Bali Digital Festival', 1, 5, 30, 'unknown'),
('https://dashboard-bmc.baliprov.go.id', 'Bali Media Center Dashboard', 'Halaman Login/ register Bali Media Center', 1, 5, 30, 'unknown'),
('https://bmc.baliprov.go.id', 'Bali Media Center', 'Media publikasi dan informasi Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://balisatudata.baliprov.go.id', 'Bali Satu Data', 'Sistem satu data Indonesia Provinsi Bali', 1, 5, 30, 'unknown'),
('https://balikom.info', 'Balikominfo', 'Smartlink milik Diskominfos Provinsi Bali', 1, 5, 30, 'unknown'),
('https://baliprov.go.id', 'Baliprov', 'Situs resmi Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bapelkesmas-diskes.baliprov.go.id', 'Bapelkesmas', 'Website resmi UPTD Bapelkesmas Diskes Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bapenda.baliprov.go.id', 'Bapenda', 'Website resmi Bapenda Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bappeda.baliprov.go.id', 'Bappeda', 'Website resmi Bappeda Provinsi Bali', 1, 5, 30, 'unknown'),
('https://birohukum.baliprov.go.id', 'Biro Hukum', 'Website Resmi Biro Hukum Setda Provnsi Bali', 1, 5, 30, 'unknown'),
('https://biroorg.baliprov.go.id', 'Biro Org', 'Website Resmi Biro Organisasi Setda Provinsi Bali', 1, 5, 30, 'unknown'),
('https://biropbjek.baliprov.go.id', 'Biro PBJEK', 'Website resmi Biro Pengadaan Barang/Jasa dan Perekonomian Setda Provinsi Bali', 1, 5, 30, 'unknown'),
('https://biropemkesra.baliprov.go.id', 'Biro Pemkesra', 'Website resmi Biro Pemerintahan dan Kesejahteraan Rakyat Setda Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bkpsdm.baliprov.go.id', 'BKPSDM', 'Website Resmi BKPSDM Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bpbd.baliprov.go.id', 'BPBD', 'Website resmi BPBD provinsi Bali', 1, 5, 30, 'unknown'),
('https://bpkad.baliprov.go.id', 'BPKAD', 'Website resmi BPKAD Provinsi Bali', 1, 5, 30, 'unknown'),
('https://brahmastra.baliprov.go.id', 'Brahmastra', 'Sistem Pendaftaran Online Pasien RSJ Provinsi Bali', 1, 5, 30, 'unknown'),
('https://brida.baliprov.go.id', 'Brida', 'Website resmi BRIDA Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bridasentraki.baliprov.go.id', 'Brida Sentraki', 'Sistem Pengelolaan Kekayaan Intelektual Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bugbounty.baliprov.go.id', 'Bug Bounty', 'Website terkait informasi penyelenggaraan Bug Bounty Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://bulanbungkarno.baliprov.go.id', 'Bulan Bung Karno', 'Website terkait informasi penyelenggaraan Bulan Bung karno Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://ceraken.baliprov.go.id', 'Ceraken', 'Sistem pengelolaan data kebudayaan Bali secara terpadu berbasis teknologi digital', 1, 5, 30, 'unknown'),
('https://csirt.baliprov.go.id', 'CSIRT', 'Website resmi Baliprov-CSIRT', 1, 5, 30, 'unknown'),
('https://ctfd.baliprov.go.id', 'CTFD', 'Platform kompetisi di bidang Cyber Security', 1, 5, 30, 'unknown'),
('https://datasektoral.baliprov.go.id', 'Data Sektoral', 'Data Sektoral adalah aplikasi berbasis web yang dikelola oleh Bidang Statistik Dinas Kominfos Provinsi Bali', 1, 5, 30, 'unknown'),
('https://disbud.baliprov.go.id', 'Disbud', 'Website resmi Disbud Provinsi Bali', 1, 5, 30, 'unknown'),
('https://disdikpora.baliprov.go.id', 'Disdikpora', 'Website resmi Disdikpora Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dishub.baliprov.go.id', 'Dishub', 'Website Resmi Dishub Provinsi Bali', 1, 5, 30, 'unknown'),
('https://diskelkan.baliprov.go.id', 'Diskelkan', 'Website resmi Diskelkan Provinsi Bali', 1, 5, 30, 'unknown'),
('https://diskes.baliprov.go.id', 'Diskes', 'Website resmi Diskes Provinsi Bali', 1, 5, 30, 'unknown'),
('https://diskominfos.baliprov.go.id', 'Diskominfos', 'Website resmi Diskominfos Provinsi Bali', 1, 5, 30, 'unknown'),
('https://diskopukm.baliprov.go.id', 'Diskopukm', 'Website resmi Diskopukm Provinsi Bali', 1, 5, 30, 'unknown'),
('https://disnakeresdm.baliprov.go.id', 'Disnakeresdm', 'Website resmi disnakeresdm Provinsi Bali', 1, 5, 30, 'unknown'),
('https://disparda.baliprov.go.id', 'Disparda', 'Website resmi Disparda Provinsi Bali', 1, 5, 30, 'unknown'),
('https://disperindag.baliprov.go.id', 'Disperindag', 'Website resmi Disperindag Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dispuprkim.baliprov.go.id', 'Dispurkim', 'Website resmi Dispuprkim Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dissosp3a.baliprov.go.id', 'Dissosp3a', 'Website resmi Dissosp3a Provinsi Bali', 1, 5, 30, 'unknown'),
('https://distanpangan.baliprov.go.id', 'Distanpangan', 'Website resmi Distanpangan Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dklh.baliprov.go.id', 'DKLH', 'Website resmi DKLH Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dpma.baliprov.go.id', 'DPMA', 'Website resmi DPMA Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dpmddukcapil.baliprov.go.id', 'DPMDDUKCAPIL', 'Website resmi DPMDDUKCAPIL Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dpmptsp.baliprov.go.id', 'DPMPTSP', 'Website Resmi DPMPTSP Provinsi Bali', 1, 5, 30, 'unknown'),
('https://drive.baliprov.go.id', 'Drive Baliprov', 'Tempat Penyimpanan File dan Dokumen secara Daring', 1, 5, 30, 'unknown'),
('https://dsdp.baliprov.go.id', 'DSDP', 'Website resmi UPTD Pengelolaan Air Limbah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://ejournal.baliprov.go.id', 'Ejournal', 'Jurnal Bali membangun Bali', 1, 5, 30, 'unknown'),
('https://eplan.baliprov.go.id', 'Eplan', 'Sistem perencanaan dan program Provinsi Bali', 1, 5, 30, 'unknown'),
('https://erelawan.baliprov.go.id', 'Erelawan', 'Website BPBD Provinsi Bali', 1, 5, 30, 'unknown'),
('https://eriset.baliprov.go.id', 'Eriset', 'Sistem Informasi Pengelolaan Riset Provinsi Bali', 1, 5, 30, 'unknown'),
('https://esakip-backend.baliprov.go.id', 'Esakip Backend', 'Sistem akuntabilitas kinerja Instansi Pemerintah secara elektronik (backend)', 1, 5, 30, 'unknown'),
('https://esakip.baliprov.go.id', 'Esakip', 'Sistem akuntabilitas kinerja Instansi Pemerintah secara elektronik (frontend)', 1, 5, 30, 'unknown'),
('https://etl.baliprov.go.id', 'eTL', 'Sistem Tindak lanjut Hasil Pemeriksaan', 1, 5, 30, 'unknown'),
('https://event.baliprov.go.id', 'Event ID', 'Platform dalam mendukung penyelenggaraan event Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://undangan.baliprov.go.id', 'Event ID Undangan', 'Platform dalam mendukung Penyelenggaraan Event Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://hadir.baliprov.go.id', 'Hadir', 'Sistem absensi kehadiran pegawai di Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://helpdesk.baliprov.go.id', 'Helpdesk', 'Helpdesk', 1, 5, 30, 'unknown'),
('https://insight.baliprov.go.id', 'Insight', 'Aplikasi Knowledge based system dan cloud storage untuk pegawai pemerintah daerah provinsi bali', 1, 5, 30, 'unknown'),
('https://inspektorat.baliprov.go.id', 'Inspektorat', 'Website resmi Inspektorat Daerah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://invest.baliprov.go.id', 'Invest', 'Sistem Pusat Investasi Kerthi Bali Sadhana Provinsi Bali', 1, 5, 30, 'unknown'),
('https://api-jdih.baliprov.go.id', 'JDIH API', 'API JDIH Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://jdih.baliprov.go.id', 'JDIH', 'Sistem yang menyajikan Dokumentasi dan Informasi Hukum Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://jidhat.baliprov.go.id', 'JIDHAT', 'Jaringan Dokumentasi Hukum Adat Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://kanal.baliprov.go.id', 'Kantor Virtual', 'Sistem Persuratan secara elektronik Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://kelasvirtual.baliprov.go.id', 'Kelas Virtual Bali Melajah', 'E-learning untuk mewujudkan SDM Bali unggul, cerdas & berkarakter', 1, 5, 30, 'unknown'),
('https://kesbangpol.baliprov.go.id', 'Kesbangpol', 'Website resmi Badan Kesbangpol Provinsi Bali', 1, 5, 30, 'unknown'),
('https://uptdkestrad.baliprov.go.id', 'Kestrad', 'Website fasilitas pelayanan kesehatan tradisional', 1, 5, 30, 'unknown'),
('https://ki.baliprov.go.id', 'KI', 'Website resmi Komisi Informasi Provinsi Bali', 1, 5, 30, 'unknown'),
('https://koperasi.baliprov.go.id', 'Koperasi', 'Sistem Online Data Koperasi Bali', 1, 5, 30, 'unknown'),
('https://kpa.baliprov.go.id', 'KPA', 'Website resmi Komisi Penanggulangan AIDS Provinsi Bali', 1, 5, 30, 'unknown'),
('https://krama.baliprov.go.id', 'Krama', 'Sistem Informasi Krama Desa Adat', 1, 5, 30, 'unknown'),
('https://layanandisdikpora.baliprov.go.id', 'Layanan Disdikpora', 'Sistem E-Kepegawaian milik Disdikpora Provinsi Bali', 1, 5, 30, 'unknown'),
('https://lenterasiber.baliprov.go.id', 'Lentera Siber', 'Website literasi keamanan siber Pemprov Bali', 1, 5, 30, 'unknown'),
('https://lovebali.baliprov.go.id', 'Love Bali', 'Platform untuk menunjang kegiatan industri pariwisata Bali', 1, 5, 30, 'unknown'),
('https://lpse.baliprov.go.id', 'LPSE', 'Website terkait layanan pengadaan secara elektronik Provinsi Bali', 1, 5, 30, 'unknown'),
('https://madeinbali.baliprov.go.id', 'Madeinbali', 'Platform yang digunakan untuk menjelajahi produk unggulan UMKM Bali', 1, 5, 30, 'unknown'),
('https://storage.baliprov.go.id', 'MinIO', 'Sistem penyimpanan objek berbasis cloud', 1, 5, 30, 'unknown'),
('https://notifikasi.baliprov.go.id', 'Notifikasi', 'Layanan Notifikasi SPBE Provinsi Bali', 1, 5, 30, 'unknown'),
('https://o2.baliprov.go.id', 'O2', 'Sistem Informasi Inventory Oksigen', 1, 5, 30, 'unknown'),
('https://officeumkm.baliprov.go.id', 'Officeumkm', 'Sistem Pendataan UMKM/IKM dan Koperasi Provinsi Bali', 1, 5, 30, 'unknown'),
('https://pameran.baliprov.go.id', 'Pameran', 'Website terkait Pameran Pembangunan Provinsi Bali', 1, 5, 30, 'unknown'),
('https://pendataan.baliprov.go.id', 'Pendataan', 'Sistem Inventori Covid', 1, 5, 30, 'unknown'),
('https://perwakilan.baliprov.go.id', 'Perwakilan', 'Website resmi Badan Penghubung Provinsi Bali', 1, 5, 30, 'unknown'),
('https://petiemas.baliprov.go.id', 'Petiemas', 'Sistem Informasi layanan pengaduan masyarakat milik Inspektorat Daerah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://portalpbj.baliprov.go.id', 'Portal PBJ', 'Portal pengadaan biro PBJEK Provinsi Bali', 1, 5, 30, 'unknown'),
('https://ppid.baliprov.go.id', 'PPID', 'Website resmi PPID Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://prestise.baliprov.go.id', 'Prestise', 'Portal Perizinan Provinsi Bali untuk memudahkan dalam pelayanan perizinan', 1, 5, 30, 'unknown'),
('https://rb.baliprov.go.id', 'Reformasi Birokrasi', 'Website Reformasi Birokrasi Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://rsbm.baliprov.go.id', 'RSBM', 'Website resmi Rumah Sakit Bali Mandara Provinsi Bali', 1, 5, 30, 'unknown'),
('https://rsjiwa.baliprov.go.id', 'RSJIWA', 'Website resmi Rumah Sakit Jiwa Provinsi Bali', 1, 5, 30, 'unknown'),
('https://rsmatabalimandara.baliprov.go.id', 'RS Mata Bali Mandara', 'Website resmi Rumah sakit Mata Bali Mandara Provinsi Bali', 1, 5, 30, 'unknown'),
('https://rumahkreatif.baliprov.go.id', 'Rumah Kreatif', 'Website resmi UPTD Rumah Kreatif dalam melayani masyarakat', 1, 5, 30, 'unknown'),
('https://satpolpp.baliprov.go.id', 'Satpol PP', 'Website resmi milik Satuan Polisi Pamong Praja Provinsi Bali', 1, 5, 30, 'unknown'),
('https://sekwandprd.baliprov.go.id', 'Sekwan DPRD', 'Website resmi Sekretariat DPRD Provinsi Bali', 1, 5, 30, 'unknown'),
('https://sensusadat.baliprov.go.id', 'Sensus Adat', 'Aplikasi Sensus Sad Kerthi Semesta Bali Berbasis Desa Adat', 1, 5, 30, 'unknown'),
('https://sibaper.baliprov.go.id', 'Sibaper', 'Sistem Informasi Terintegrasi milik Biro PBJ Setda Provinsi Bali', 1, 5, 30, 'unknown'),
('https://dashboard-sigapura.baliprov.go.id', 'Sigapura Dashboard', 'Admin Sistem Harga Pangan antar Daerah Bali', 1, 5, 30, 'unknown'),
('https://sigapura.baliprov.go.id', 'Sigapura', 'Sistem Harga Pangan antar Daerah Bali', 1, 5, 30, 'unknown'),
('https://sigenting.baliprov.go.id', 'Sigenting', 'Sistem informasi untuk mendata dan memantau balita berisiko stunting', 1, 5, 30, 'unknown'),
('https://sik-kbs.baliprov.go.id', 'SIK-KBS', 'Sistem informasi terkait layanan kesehatan Provinsi Bali', 1, 5, 30, 'unknown'),
('https://sika.baliprov.go.id', 'SIKA', 'Sistem Informasi Kompentensi Aparatur', 1, 5, 30, 'unknown'),
('https://sikepo.baliprov.go.id', 'SIKEPO', 'Aplikasi yang mencatat seluruh kegiatan harian dari pegawai di lingkup Pemprov Bali', 1, 5, 30, 'unknown'),
('https://sikuat.baliprov.go.id', 'Sikuat', 'Sistem keuangan desa adat', 1, 5, 30, 'unknown'),
('https://sikuat-statistik.baliprov.go.id', 'Sikuat-statistik', 'Data statistik keuangan desa adat', 1, 5, 30, 'unknown'),
('https://silebah.baliprov.go.id', 'Silebah', 'Sistem Informasi dan Pelayanan Online Pengujian Laboratorium', 1, 5, 30, 'unknown'),
('https://simata.baliprov.go.id', 'Simata', 'Sistem manajemen Talenta pegawai daerah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://simpeg.baliprov.go.id', 'Simpeg', 'Sistem yang digunakan dalam manajemen data dan informasi kepegawaian', 1, 5, 30, 'unknown'),
('https://simpeg-ng.baliprov.go.id', 'Simpeg Staging', 'Simpeg staging environment untuk kebutuhan pengembangan dan pengujian', 1, 5, 30, 'unknown'),
('https://simpelkan.baliprov.go.id', 'Simpelkan', 'Sistem berbasis website untuk memperbaiki kualitas pelayanan di bidang perikanan', 1, 5, 30, 'unknown'),
('https://simrsbm-test.baliprov.go.id', 'SIMRSBM', 'Sistem Informasi Manajemen Rumah Sakit', 1, 5, 30, 'unknown'),
('https://sipance.baliprov.go.id', 'Sipance', 'Portal layanan perizinan Provinsi Bali', 1, 5, 30, 'unknown'),
('https://sipay.baliprov.go.id', 'Sipay', 'Sistem pembayaran online yang menyediakan API koneksi', 1, 5, 30, 'unknown'),
('https://siri.baliprov.go.id', 'SIRI', 'Aplikasi Sistem Inventori', 1, 5, 30, 'unknown'),
('https://labkes.baliprov.go.id', 'SISLABKES', 'Sistem Laboratorium Kesehatan Provinsi Bali', 1, 5, 30, 'unknown'),
('https://sisnaker.baliprov.go.id', 'Sisnaker', 'Sistem Layanan Publik di Bidang ketenagakerjaan', 1, 5, 30, 'unknown'),
('https://stunting.baliprov.go.id', 'Sistem Monitoring Stunting', 'Aplikasi monitoring perkembangan stunting di Provinsi Bali', 1, 5, 30, 'unknown'),
('https://siwalatri.baliprov.go.id', 'Siwalatri', 'Aplikasi untuk pengawasan dan pelaporan pramuwisata', 1, 5, 30, 'unknown'),
('https://slbn1bangli.baliprov.go.id', 'SLBN1 Bangli', 'Website resmi SLB N 1 Bangli', 1, 5, 30, 'unknown'),
('https://slbn1karangasem.baliprov.go.id', 'SLBN1 Karangasem', 'Website resmi SLB N 1 Karangasem', 1, 5, 30, 'unknown'),
('https://slbn1klungkung.baliprov.go.id', 'SLBN1 Klungkung', 'Website resmi SLB N 1 Klungkung', 1, 5, 30, 'unknown'),
('https://slbn1tabanan.baliprov.go.id', 'SLBN1 Tabanan', 'Website resmi SLB N 1 Tabanan', 1, 5, 30, 'unknown'),
('https://sso.baliprov.go.id', 'SSO', 'Satu login untuk semua aplikasi di Pemprov Bali', 1, 5, 30, 'unknown'),
('https://supermankuat.baliprov.go.id', 'SUPERMAN KUAT', 'Aplikasi strategi penguatan penerapan manajemen risiko', 1, 5, 30, 'unknown'),
('https://swastisaba.baliprov.go.id', 'Swastisaba', 'Swastisaba', 1, 5, 30, 'unknown'),
('https://tarubali.baliprov.go.id', 'Tarubali', 'Sistem Informasi Wilayah dan Tata Ruang Bali', 1, 5, 30, 'unknown'),
('https://tjsl.baliprov.go.id', 'TJSL', 'Website tentang program TJSL pembangunan berkelanjutan', 1, 5, 30, 'unknown'),
('https://var.baliprov.go.id', 'Virtual & Augmented Reality', 'Website Informasi Teknologi Virtual Reality dan Augmented Reality', 1, 5, 30, 'unknown'),
('https://virtualtour360.baliprov.go.id', 'Virtual Tour 360', 'Platform interaktif untuk menjelajahi keindahan Bali dalam tampilan 360 derajat', 1, 5, 30, 'unknown'),
('https://wbs.baliprov.go.id', 'WBS', 'Whistleblowing System Pemprov Bali', 1, 5, 30, 'unknown'),
('https://slbnegeri2buleleng.baliprov.go.id', 'SLBN 2 Buleleng', 'Website resmi SLB Negeri 2 Buleleng', 1, 5, 30, 'unknown'),
('https://slbn3denpasar.baliprov.go.id', 'SLBN 3 Denpasar', 'Website resmi SLB Negeri 3 Denpasar', 1, 5, 30, 'unknown'),
('https://uptdppmhp.baliprov.go.id', 'UPTD PPMHP', 'Website resmi UPTD Pengujian dan Penerapan Mutu Hasil Perikanan', 1, 5, 30, 'unknown'),
('https://yandibali.baliprov.go.id', 'Yandi Bali', 'Layanan persandian Pemerintah Provinsi Bali', 1, 5, 30, 'unknown'),
('https://perisai.baliprov.go.id', 'Perisai', 'PERISAI sistem elektronik untuk PEngelolaan RISiko Aset Informasi', 1, 5, 30, 'unknown');
